EC2Instance1:
  Type: AWS::EC2::Instance
  Properties:
    InstanceType:
      Ref: InstanceType
    SecurityGroups:
      - Ref: InstanceSecurityGroup
    KeyName:
      Ref: KeyName
    ImageId:
      Fn::FindInMap:
        - AWSRegionArch2AMI
        - Ref: AWS::Region
        - Fn::FindInMap:
          - AWSInstanceType2Arch
          - Ref: InstanceType
          - Arch

EC2Instance2:
  Type: AWS::EC2::Instance
  Properties:
    InstanceType:
      Ref: InstanceType
    SecurityGroups:
      - Ref: InstanceSecurityGroup
    KeyName:
      Ref: KeyName
    ImageId:
      Fn::FindInMap:
        - AWSRegionArch2AMI
        - Ref: AWS::Region
        - Fn::FindInMap:
          - AWSInstanceType2Arch
          - Ref: InstanceType
          - Arch

EC2Instance3:
  Type: AWS::EC2::Instance
  Properties:
    InstanceType:
      Ref: InstanceType
    SecurityGroups:
      - Ref: InstanceSecurityGroup
    KeyName:
      Ref: KeyName
    ImageId:
      Fn::FindInMap:
        - AWSRegionArch2AMI
        - Ref: AWS::Region
        - Fn::FindInMap:
          - AWSInstanceType2Arch
          - Ref: InstanceType
          - Arch
