AWSTemplateFormatVersion: '2010-09-09'
Description: |
  Creates an EC2 instance with a security group.
  Based on AWS sample template "EC2InstanceWithSecurityGroupSample",
      which is available at https://amzn.to/2WdaX2i.

Parameters:
  StagingBucket:
    Description: Bucket where templates are staged
    Type: String

  Environment:
    Description: Application environment
    Type: String
    Default: test
    AllowedValues:
      - test
      - prod

  OperatingSystem:
    Description: Chosen operating system
    Type: String
    Default: AmazonLinux2
    AllowedValues:
      - AmazonLinux2
      - Windows2016Base

  InstanceType:
    Description: EC2 instance type
    Type: String
    Default: t2.small
    AllowedValues:
      - t2.nano
      - t2.micro
      - t2.small
      - t2.medium
      - m4.large
      - m4.xlarge
    ConstraintDescription: must be a valid EC2 instance type.

  PublicLocation:
    Description: The IP address range that can be used to connect to the EC2 instances
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: '0.0.0.0/0'
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.

Mappings:
  'Fn::Transform':
    Name: 'AWS::Include'
    Parameters:
      Location: !Sub "s3://${StagingBucket}/mappings/${Environment}.yml"
  Global:
    ConnectPortByOs:
      Windows2016Base: 3389
      AmazonLinux2: 22

Resources:
  EC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      InstanceType: !Ref 'InstanceType'
      SecurityGroups:
        - !Ref 'InstanceSg'
      KeyName: !FindInMap [ 'Keypair', !Ref "AWS::Region", 'Name' ]
      ImageId: !FindInMap [ 'AmiByOs', !Ref "AWS::Region", !Ref OperatingSystem ]

  InstanceSg:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: Enable public access via OS-specific port
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: !FindInMap
            - 'Global'
            - 'ConnectPortByOs'
            - !Ref 'OperatingSystem'
          ToPort: !FindInMap
            - 'Global'
            - 'ConnectPortByOs'
            - !Ref 'OperatingSystem'
          CidrIp: !Ref 'PublicLocation'

Outputs:
  InstanceId:
    Description: InstanceId of the EC2 instance
    Value: !Ref EC2Instance

  AZ:
    Description: AZ of the EC2 instance
    Value: !GetAtt 'EC2Instance.AvailabilityZone'

  PublicDNS:
    Description: Public DNSName of the EC2 instance
    Value: !GetAtt 'EC2Instance.PublicDnsName'

  PublicIP:
    Description: Public IP address of the EC2 instance
    Value: !GetAtt 'EC2Instance.PublicIp'
